### PR TITLE
Gibbs Sampling

### PR DESCRIPTION
**Pull request by AnthonyPerez8**
Gibbs sampling was implemented in gibbs.jl.
Unit tests are under test_gibbs.jl.  runtests.jl was modified to run tests under test_gibbs.jl.
Methods for getting the Markov blanket of a variable and for getting all cpds containing a variable were added to bayes_nets.jl.
An abstract type named BayesNetSampler was added to sampling.jl.  This should be used to call methods of the form Base.rand(bn::BayesNet, config::BayesNetSampler, nsamples::Integer).
The appropriate things should be exported in BayesNets.jl.

The Gibbs sampling implementation has two access points.  gibbs_sample and Base.rand(bn::BayesNet, config::GibbsSampler, nsamples::Integer).  Base.rand(bn::BayesNet, config::GibbsSampler, nsamples::Integer) is a wrapper for gibbs_sample but allows the GibbsSampler type to store all of the parameters.  Internally, the Gibbs sampler uses Metropolis Hastings when the posterior distributions it needs to sample from are continuous.  For distributions with finite support, the Gibbs sample builds the exact distribution and then samples from it.

### CODE REVIEW

**Comment by tawheeler** [comment]
Looks like this isn't backwards compatible with Julia 0.4.
Would it be difficult to support 0.4 functionality?

**Comment by AnthonyPerez8** [comment]
Ok, this compatibility issues should be resolved.
If you're curious, the issue was that I was using a Dictionary constructor syntax added in 0.5.  Dict(x for x in y) does not work in 0.4 .  0.4 requires Dict([x for x in y]).  However this is deprecated in 0.5, so I just went with a for loop.

**Comment by tawheeler** [comment]
Perfect, thank you

**Comment by AnthonyPerez8** [comment]
I'm happy to be able to contribute. 👍

**Pull request merged**
