### PR TITLE
BN domains support strings and integers

### PR DESCRIPTION
**Pull request by ermueller2000**
This version should pass all the tests.  There is also now a test case for string domains.

### CODE REVIEW

**Comment by ermueller2000** [comment]
Looks like the code works, but now my "coverage" is insufficient?  I added a test for the new domains, suggestions on how to improve coverage?

**Comment by mykelk** [comment]
I think you just need to test that exercises line 170 of io.jl as indicated [here](https://coveralls.io/builds/4660246/source?filename=src%2Fio.jl).

**Comment by ermueller2000** [comment]
I'll have to try again tomorrow...  Not sure how to test the rejected samples part of rand_table().

**Comment by mykelk** [comment]
I'm fine with a merge.

**Comment by tawheeler** [comment]
Thanks!

**Pull request merged**
