### PR TITLE
RFC: first cut at LightGraphs implementation

### PR DESCRIPTION
**Pull request by sbromberger**
Hi,

I wanted to see whether LightGraphs provided more performance for BayesNets, so I took the liberty of 1) fixing BayesNets to work on 0.4 (`Range1` is no longer valid), and 2) reimplementing the DAGs as `LightGraphs.DiGraph` instead of `simple_graph`. The good news is that things like edge removal are built into LightGraphs; this makes several functions much simpler. There's probably a good deal more optimization we could do but I wanted to gauge interest before spending a whole lot more time on this. Please let me know.

PS: things like plotting might not work yet due to the dependency on TikzGraphs and the fact that TikzGraphs doesn't grok LightGraphs yet. That can certainly be fixed.

### CODE REVIEW

**Comment by mykelk** [comment]
Thanks for your contribution. I'm interested in what you have done. It would be great if we can get it to display properly using tikzgraphs.

**Comment by sbromberger** [comment]
It's easy enough to do. The quick way is just to convert a LightGraphs.DiGraph to a Graphs.simple_graph:
```
s = simple_graph(nv(g), is_directed=LightGraphs.is_directed(g))
for e in LightGraphs.edges(g)
    add_edge!(s,src(e), dst(e))
end
```
...and then call `plot()`.

The "better" way is for me to create a PR for tikzgraphs that will take a LightGraphs.SimpleGraph type. I can do that tonight / tomorrow. It's fairly straightforward.

**Comment by mykelk** [comment]
Sounds good to me. Thanks!

**Comment by sbromberger** [comment]
I wonder if it could be this straightforward: https://github.com/sisl/TikzGraphs.jl/pull/1

**Pull request merged**
