### PR TITLE
Improved bayesian_score_component performance when using a uniform prior

### PR DESCRIPTION
**Pull request by ShadovvMoon**
As part of my final project for CS238 (2016) I have created a new discrete structure learning algorithm. I also improved the bayesian_score_component performance when using a uniform prior to a point where it is practical to use the BayesNet framework for assignment scoring.

### CODE REVIEW

**Comment by ShadovvMoon** [comment]
It would appear that my code is incompatible with Julia 0.4 and I believe that changing the line in question would incur a significant performance penalty  :( 
```
sN = sum(N[i,:] for i=1:ncategories[I])
```

**Comment by mykelk** [comment]
Can't `sN = sum(N[i,:] for i=1:ncategories[I])` be converted to `sum(N[1:ncategories[I],:])`?

**Comment by ShadovvMoon** [comment]
Nope - that would sum up all of the elements in the array. To achieve the same effect one would need to add an additional 1 argument to sum (so it sums columns rather than everything), but this causes the result to be a dense vector for whatever reason. It seems to convert the columns of N to dense vectors (very bad idea when N is large) before summing them together. 
```
sum(N[1:ncategories[i],:], 1)
```
To be a direct replacement you could wrap it in a sparsevec but this means the sum calculation still uses dense vectors.
```
sN = sparsevec(sum(N[1:ncategories[i],:], 1))
```
The original sums up a bunch of sparse vectors to create a new sparse vector. As the columns of N are sparse, this is much, much faster. 
```
sN = sum(N[i,:] for i=1:ncategories[I])
```

**Comment by mykelk** [comment]
Would `@simd` or `@inbounds` help your loop run faster?

**Comment by ShadovvMoon** [comment]
Didn't seem to speed up the loop :( A node with 25 parents (each with two possible values) takes the following time to evaluate with different ```sN``` calculators: 

0.46 seconds (17.11 seconds with 30 parents)
```sN = sum(N[i,:] for i=1:ncategories[I])```

1.14 seconds (62.4 seconds with 30 parents)
```sN = sparsevec(sum(N[1:ncategories[i],:], 1))```

18.06 seconds (10 min with 30 parents)
```
sN = spzeros(size(N, 2), 1)
@simd for i=1:ncategories[i]
    @inbounds sN += N[i,:]
end
```

**Comment by mykelk** [comment]
Personally, I'm okay at this point dropping support for 0.4, but I'll defer to @tawheeler. If we do that, then we need this to be reflected in REQUIRE and tag a minor version. Another option is to use `@static` and branch on the version number.

**Comment by ShadovvMoon** [comment]
A branch on the version number is probably a better idea. Even the slower
```sN = sparsevec(sum(N[1:ncategories[i],:], 1))``` is up to 5x faster than the original when using a uniform prior.

**Comment by mykelk** [comment]
Cool. Let's do that.

**Comment by ShadovvMoon** [comment]
Hmm... Is there a way to make Julia avoid parsing that syntax? Ideally without using eval 😨

**Comment by tawheeler** [comment]
Hmm, not sure. Does Compat.jl provide functionality for this?

**Comment by tawheeler** [comment]
I posted on the Julia users page. We'll see if they have a suggestion.

**Comment by tawheeler** [comment]
Sounds like the only alternative is to conditionally include the files. That sounds like more trouble than it is worth.
We were going to drop 0.4 support once 0.6 was released, but this could be a good reason to do it earlier.

**Comment by mykelk** [comment]
I'm happy to drop 0.4, @tawheeler, whenever you're comfortable.

**Comment by tawheeler** [comment]
Will merge and then update BayesNets to only support 0.5

**Pull request merged**
