### PR TITLE
use version number instead of release in .travis.yml

### PR DESCRIPTION
**Pull request by tkelman**
release will change over time, but your REQUIRE file says this package supports julia 0.5 so it should continue to be tested

### CODE REVIEW

**Comment by mykelk** [comment]
Looks like things break with Julia 0.6:
```
ERROR: LoadError: LoadError: LoadError: syntax: "BayesNets.CPDs.cpd" is not a valid function argument name
```

**Comment by tkelman** [comment]
commit message is a little wrong on this one, I just wanted something to replace `release` with - if the package isn't ready for 0.6 then no worries, just be aware that I plan on deprecating and removing the `release` option on Travis before too long

**Comment by mykelk** [comment]
Ah, got it. I think one of my students should be able to get this ready for 0.6 pretty quickly.

**Comment by tawheeler** [comment]
I can do this after Thursday. 
We need to discuss who can take over BayesNets. (and Hamza's factor package)

**Pull request closed without merging**
